/*
ALUMNO: ERICK FABRICIO MARTINEZ CASTELLANOS
CUENTA: 20121005657
*/

/* BASE DE DATOS DE SUPERMERCADO */


--CREATE DATABASE SUPERMERCADO


USE SUPERMERCADO


/************ TABLAS DE UBICACION ************/ 

CREATE TABLE PAIS
(
	ID_PAIS INT NOT NULL,
	NOMBRE_PAIS VARCHAR(50) NULL,

	CONSTRAINT PK_ID_PAIS PRIMARY KEY (ID_PAIS),
	CONSTRAINT CK_ID_PAIS CHECK (ID_PAIS > 0)
	
)


CREATE TABLE DEPARTAMENTO
(
	ID_DEPARTAMENTO INT NOT NULL,
	NOMBRE_DEPARTAMENTO VARCHAR(50) NULL,
	ID_PAIS_DEPARTAMENTO INT NULL,

	CONSTRAINT PK_ID_DEPARTAMENTO PRIMARY KEY (ID_DEPARTAMENTO),
	CONSTRAINT CK_ID_DEPARTAMENTO CHECK (ID_DEPARTAMENTO > 0)
)


CREATE TABLE CIUDAD
(
	ID_CIUDAD INT NOT NULL,
	NOMBRE_CIUDAD VARCHAR(50) NULL,
	ID_DEPARTAMENTO_CIUDAD INT NULL,

	CONSTRAINT PK_ID_CIUDAD PRIMARY KEY (ID_CIUDAD),
	CONSTRAINT CK_ID_CIUDAD CHECK (ID_CIUDAD > 0)
	
)



/************ TABLAS RELACIONAS CON PERSONAS ************/

CREATE TABLE PERSONA
(
	ID_PERSONA INT NOT NULL,
	PRIMER_NOMBRE_PERSONA VARCHAR(20) NULL,
	SEGUNDO_NOMBRE_PERSONA VARCHAR(20) NULL,
	PRIMER_APELLIDO_PERSONA VARCHAR(20) NULL,
	SEGUNDO_APELLIDO_PERSONA VARCHAR(20) NULL,
	FECHA_NACIMIENTO_PERSONA DATE NULL,
	NUMERO_IDENTIDAD_PERSONA VARCHAR(20) NULL,
	DIRECCION_RESIDENCIA_PERSONA TEXT NULL,
	ID_CIUDAD_RESIDENCIA_PERSONA INT NULL,
	ID_SEXO_PERSONA INT NULL,

	CONSTRAINT PK_ID_PERSONA PRIMARY KEY (ID_PERSONA),
	CONSTRAINT UQ_NUMERO_IDENTIDAD_PERSONA UNIQUE (NUMERO_IDENTIDAD_PERSONA),
	CONSTRAINT CK_ID_PERSONA CHECK (ID_PERSONA > 0)

)


CREATE TABLE SEXO
(
	ID_SEXO INT NOT NULL,  
	SEXO VARCHAR(20) NULL,
	
	CONSTRAINT PK_ID_SEXO PRIMARY KEY (ID_SEXO),
	CONSTRAINT CK_ID_SEXO CHECK (ID_SEXO > 0)
)


CREATE TABLE EMPLEADO
(
	ID_EMPLEADO INT NOT NULL,
	FECHA_CONTRATACION_EMPLEADO DATE NULL,
	HORAS_LABORALES_MENSUALES_EMPLEADO INT NULL,
	ID_PERSONA_EMPLEADO INT NULL,
	ID_CARGO_LABORAL_EMPLEADO INT NULL,
	ID_SUCURSAL_EMPLEADO INT NULL,
	
	CONSTRAINT PK_ID_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
	CONSTRAINT UQ_ID_PERSONA_EMPLEADO UNIQUE (ID_PERSONA_EMPLEADO),
	CONSTRAINT CK_ID_EMPLEADO CHECK (ID_EMPLEADO > 0),
	CONSTRAINT CK_HORAS_LABORALES_MENSUALES_EMPLEADO CHECK (HORAS_LABORALES_MENSUALES_EMPLEADO > 0)
)


CREATE TABLE CARGO_LABORAL
(
	ID_CARGO_LABORAL INT NOT NULL,
	CARGO_LABORAL VARCHAR(30) NULL,
	DESCRIPCION_CARGO_LABORAL TEXT NULL,
	SALARIO_MENSUAL_CARGO_LABORAL FLOAT NULL,

	CONSTRAINT PK_ID_CARGO_LABORAL PRIMARY KEY (ID_CARGO_LABORAL),
	CONSTRAINT CK_ID_CARGO_LABORAL CHECK (ID_CARGO_LABORAL > 0),
	CONSTRAINT CK_SALARIO_MENSUAL_CARGO_LABORAL CHECK (SALARIO_MENSUAL_CARGO_LABORAL > 0)
)


CREATE TABLE CLIENTE
(
	ID_CLIENTE INT NOT NULL,
	ID_PERSONA_CLIENTE INT NULL,

	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT UQ_ID_PERSONA_CLIENTE UNIQUE (ID_PERSONA_CLIENTE),
	CONSTRAINT CK_ID_CLIENTE CHECK (ID_CLIENTE > 0)
)



/************ TABLAS RELACIONADAS CON LOS PRODUCTOS ************/

CREATE TABLE PRODUCTO
(
	ID_PRODUCTO INT NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(30) NULL,
	FECHA_ELABORACION_PRODUCTO DATE NULL,
	FECHA_VENCIMIENTO_PRODUCTO DATE NULL,
	COMPRA_PRODUCTO FLOAT NULL,
	VENTA_PRODUCTO FLOAT NULL,
	CANTIDAD_PRODUCTO INT NULL,
	DESCRIPCION_PRODUCTO TEXT NULL,
	ID_TIPO_PRODUCTO INT NULL,
	ID_SUCURSAL_PRODUCTO INT NULL,

	CONSTRAINT PK_ID_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
	CONSTRAINT CK_ID_PRODUCTO CHECK (ID_PRODUCTO > 0),
	CONSTRAINT CK_COMPRA_PRODUCTO CHECK (COMPRA_PRODUCTO > 0),
	CONSTRAINT CK_VENTA_PRODUCTO CHECK (VENTA_PRODUCTO > 0),
	CONSTRAINT CK_CANTIDAD_PRODUCTO CHECK (CANTIDAD_PRODUCTO > 0)
)


CREATE TABLE TIPO_PRODUCTO
(
	ID_TIPO_PRODUCTO INT NOT NULL,
	TIPO_PRODUCTO VARCHAR(20) NULL,
	DESCRIPCION_TIPO_PRODUCTO TEXT NULL,

	CONSTRAINT PK_ID_TIPO_PRODUCTO PRIMARY KEY (ID_TIPO_PRODUCTO),
	CONSTRAINT CK_ID_TIPO_PRODUCTO CHECK (ID_TIPO_PRODUCTO > 0)
)


CREATE TABLE PROVEEDOR 
(
	ID_PROVEEDOR INT NOT NULL,
	NOMBRE_PROVEEDOR VARCHAR(50) NULL,

	CONSTRAINT PK_ID_PROVEEDOR PRIMARY KEY (ID_PROVEEDOR),
	CONSTRAINT CK_ID_PROVEEDOR CHECK (ID_PROVEEDOR > 0)
)


CREATE TABLE PRODUCTO_PROVEEDOR
(
	ID_PRODUCTO INT  NOT NULL,
	ID_PROVEEDOR INT NOT NULL,

	CONSTRAINT PK_ID_PRODUCTO_ID_PROVEEDOR PRIMARY KEY (ID_PRODUCTO,ID_PROVEEDOR)
)


CREATE TABLE SUCURSAL 
(
	ID_SUCURSAL INT NOT NULL,
	NOMBRE_SUCURSAL VARCHAR(50) NULL,
	ID_CIUDAD_SUCURSAL INT NULL,

	CONSTRAINT PK_ID_SUCURSAL PRIMARY KEY (ID_SUCURSAL),
	CONSTRAINT CK_ID_SUCURSAL CHECK (ID_SUCURSAL > 0)
)



/************ TABLAS RELACIONADAS A LA FACTURACION Y TELEFONIA ************/

CREATE TABLE FACTURA
(
	ID_FACTURA INT NOT NULL,
	FECHA_FACTURA DATE NULL,
	ID_SUCURSAL_FACTURA INT NULL,
	ID_CLIENTE_FACTURA INT NULL,
	ID_EMPLEADO_FACTURA INT NULL,

	CONSTRAINT PK_ID_FACTURA PRIMARY KEY (ID_FACTURA),
	CONSTRAINT CK_ID_FACTURA CHECK (ID_FACTURA > 0)
)


CREATE TABLE FACTURA_PRODUCTO
(
	ID_FACTURA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD_PRODUCTO INT NULL,

	CONSTRAINT PK_ID_FACTURA_ID_PRODUCTO PRIMARY KEY (ID_FACTURA,ID_PRODUCTO),
	CONSTRAINT CK_CANTIDAD_PRODUCTOS CHECK (CANTIDAD_PRODUCTO > 0)
)


CREATE TABLE TIPO_TELEFONO
(
	ID_TIPO_TELEFONO INT NOT NULL,
	TIPO_TELEFONO VARCHAR(30) NULL,
	DESCRIPCION_TIPO_TELEFONO TEXT NULL,

	CONSTRAINT PK_ID_TIPO_TELEFONO PRIMARY KEY (ID_TIPO_TELEFONO),
	CONSTRAINT CK_ID_TIPO_TELEFONO CHECK (ID_TIPO_TELEFONO > 0)
)


CREATE TABLE TELEFONO
(
	ID_TELEFONO INT NOT NULL,
	TELEFONO VARCHAR(20) NULL,
	ID_TIPO_TELEFONO INT NULL,
	ID_PERSONA_TELEFONO INT NULL,

	CONSTRAINT PK_ID_TELEFONO PRIMARY KEY (ID_TELEFONO),
	CONSTRAINT UQ_TELEFONO UNIQUE (TELEFONO),
	CONSTRAINT CK_ID_TELEFONO CHECK (ID_TELEFONO > 0)
)


/************ TABLAS DE USUARIO ************/

CREATE TABLE USUARIO
(
	ID_USUARIO INT NOT NULL,
	NOMBRE_USUARIO VARCHAR(20) NOT NULL,
	CONTRASENA_USUARIO VARBINARY(100) NOT NULL,
	ID_TIPO_USUARIO INT NULL,
	ID_PERSONA_USUARIO INT NULL,

	CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO),
	CONSTRAINT UQ_ID_NOMBRE_USUARIO UNIQUE (NOMBRE_USUARIO),
	CONSTRAINT CK_ID_USUARIO CHECK (ID_USUARIO > 0)
)


CREATE TABLE TIPO_USUARIO
(
	ID_TIPO_USUARIO INT NOT NULL,
	DESCRIPCION_TIPO_USUARIO TEXT NULL,

	CONSTRAINT PK_ID_TIPO_USUARIO PRIMARY KEY (ID_TIPO_USUARIO),
	CONSTRAINT CK_ID_TIPO_USUARIO CHECK (ID_TIPO_USUARIO > 0)
)


CREATE TABLE ROL_SERVIDOR
(
	ID_ROL_SERVIDOR INT NOT NULL,
	DESCRIPCION_ROL_SERVIDOR TEXT NULL,

	CONSTRAINT PK_ID_ROL_SERVIDOR PRIMARY KEY (ID_ROL_SERVIDOR),
	CONSTRAINT CK_ID_ROL_SERVIDOR CHECK (ID_ROL_SERVIDOR > 0)
)


CREATE TABLE ROL_BD
(
	ID_ROL_BD INT NOT NULL,
	DESCRIPCION_ROL_BD TEXT NULL,

	CONSTRAINT PK_ID_ROL_BD PRIMARY KEY (ID_ROL_BD),
	CONSTRAINT CK_ID_ROL_BD CHECK (ID_ROL_BD > 0)
)


CREATE TABLE USUARIO_ROL_SERVIDOR
(
	ID_USUARIO INT NOT NULL,
	ID_ROL_SERVIDOR INT NOT NULL,

	CONSTRAINT PK_ID_USUARIO_ID_ROL_SERVIDOR PRIMARY KEY (ID_USUARIO,ID_ROL_SERVIDOR)
)


CREATE TABLE USUARIO_ROL_BD
(
	ID_USUARIO INT NOT NULL,
	ID_ROL_BD INT NOT NULL,

	CONSTRAINT PK_ID_USUARIO_ID_ROL_BD PRIMARY KEY (ID_USUARIO,ID_ROL_BD)
)




 /************ CREANDO LLAVES SECUNDARIAS Y RELACIONES ************/

ALTER TABLE DEPARTAMENTO ADD 
	CONSTRAINT FK_ID_PAIS_DEPARTAMENTO FOREIGN KEY (ID_PAIS_DEPARTAMENTO) REFERENCES PAIS(ID_PAIS)


ALTER TABLE CIUDAD ADD 
	CONSTRAINT FK_ID_DEPARTAMENTO_CIUDAD FOREIGN KEY (ID_DEPARTAMENTO_CIUDAD) REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO)


ALTER TABLE PERSONA ADD 
	CONSTRAINT FK_ID_CIUDAD_RESIDENCIA_PERSONA FOREIGN KEY (ID_CIUDAD_RESIDENCIA_PERSONA) REFERENCES CIUDAD(ID_CIUDAD),
	CONSTRAINT FK_ID_SEXO_PERSONA FOREIGN KEY (ID_SEXO_PERSONA) REFERENCES SEXO(ID_SEXO)


ALTER TABLE EMPLEADO ADD
	CONSTRAINT FK_ID_PERSONA_EMPLEADO FOREIGN KEY (ID_PERSONA_EMPLEADO) REFERENCES PERSONA(ID_PERSONA),
	CONSTRAINT FK_ID_CARGO_LABORAL_EMPLEADO FOREIGN KEY (ID_CARGO_LABORAL_EMPLEADO) REFERENCES CARGO_LABORAL(ID_CARGO_LABORAL),
	CONSTRAINT FK_ID_SUCURSAL_EMPLEADO FOREIGN KEY (ID_SUCURSAL_EMPLEADO) REFERENCES SUCURSAL(ID_SUCURSAL)


ALTER TABLE CLIENTE ADD
	CONSTRAINT FK_ID_PERSONA_CLIENTE FOREIGN KEY (ID_PERSONA_CLIENTE) REFERENCES PERSONA(ID_PERSONA)


ALTER TABLE PRODUCTO ADD 
	CONSTRAINT FK_ID_TIPO_PRODUCTO FOREIGN KEY (ID_TIPO_PRODUCTO) REFERENCES TIPO_PRODUCTO(ID_TIPO_PRODUCTO),
	CONSTRAINT FK_ID_SUCURSAL_PRODUCTO FOREIGN KEY (ID_SUCURSAL_PRODUCTO) REFERENCES SUCURSAL(ID_SUCURSAL)


ALTER TABLE PRODUCTO_PROVEEDOR ADD
	CONSTRAINT FK_ID_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
	CONSTRAINT FK_ID_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR) 
	

ALTER TABLE SUCURSAL ADD
	CONSTRAINT FK_ID_CIUDAD_SUCURSAL FOREIGN KEY (ID_CIUDAD_SUCURSAL) REFERENCES CIUDAD(ID_CIUDAD) 


ALTER TABLE FACTURA ADD
	CONSTRAINT FK_ID_SUCURSAL_FACTURA FOREIGN KEY (ID_SUCURSAL_FACTURA) REFERENCES SUCURSAL(ID_SUCURSAL), 
	CONSTRAINT FK_ID_CLIENTE_FACTURA FOREIGN KEY (ID_CLIENTE_FACTURA) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_ID_EMPLEADO_FACTURA FOREIGN KEY (ID_EMPLEADO_FACTURA) REFERENCES EMPLEADO(ID_EMPLEADO)


ALTER TABLE FACTURA_PRODUCTO ADD
	CONSTRAINT FK_ID_FACTURAS FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA),
	CONSTRAINT FK_ID_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)


ALTER TABLE TELEFONO ADD
	CONSTRAINT FK_ID_TIPO_TELEFONO FOREIGN KEY (ID_TIPO_TELEFONO) REFERENCES TIPO_TELEFONO(ID_TIPO_TELEFONO),
	CONSTRAINT FK_ID_PERSONA_TELEFONO FOREIGN KEY (ID_PERSONA_TELEFONO) REFERENCES PERSONA(ID_PERSONA)
	 

ALTER TABLE USUARIO ADD
	CONSTRAINT FK_ID_PERSONA_USUARIO FOREIGN KEY (ID_PERSONA_USUARIO) REFERENCES PERSONA(ID_PERSONA),
	CONSTRAINT FK_ID_TIPO_USUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO)


ALTER TABLE USUARIO_ROL_SERVIDOR ADD
	CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_ID_ROL_SERVIDOR FOREIGN KEY (ID_ROL_SERVIDOR) REFERENCES ROL_SERVIDOR(ID_ROL_SERVIDOR) 


ALTER TABLE USUARIO_ROL_BD ADD
	CONSTRAINT FK_ID_USUARIOS FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_ID_ROL_BD FOREIGN KEY (ID_ROL_BD) REFERENCES ROL_BD(ID_ROL_BD) 