/*
ALUMNO: ERICK FABRICIO MARTINEZ CASTELLANOS
CUENTA: 20121005657
*/

/* BASE DE DATOS DE SUPERMERCADO */

--INSERTS 


USE SUPERMERCADO


/************ TABLAS DE UBICACION ************/ 

--TABLA PAIS

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (1,'HONDURAS')

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (2,'NICARAGUA')

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (3,'EL SALVADOR')

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (4,'COSTA RICA')

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (5,'PANAMA')

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (6,'GUATEMALA')

INSERT INTO [SUPERMERCADO].[dbo].[PAIS]
	VALUES (7,'BELICE')



--TABLA DEPARTAMENTO

--HONDURAS
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (1,'CORTES',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (2,'GRACIAS A DIOS',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (3,'COPAN',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (4,'YORO',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (5,'OLANCHO',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (6,'LEMPIRA',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (7,'OCOTEPEQUE',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (8,'VALLE ',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (9,'FRANCISCO MORAZAN',1)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (10,'CHOLUTECA',1)


--NICARAGUA
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (11,'LEON',2)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (12,'MANAGUA',2)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (13,'MASAYA',2)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (14,'GRANADA',2)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (15,'RIVAS',2)


--EL SALVADOR
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (16,'SAN SALVADOR',3)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (17,'CUSCATLAN',3)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (18,'MORAZAN',3)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (19,'LA LIBERTAD',3)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (20,'SAN MIGUEL',3)


--COSTA RICA
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (21,'SAN JOSE',4)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (22,'CARTAGO',4)


--PANAMA
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (23,'PANAMA',5)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (24,'COLON',5)


--GUATEMALA
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (25,'GUATEMALA',6)


--BELICE
INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (26,'CAYO',7)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (27,'BELICE',7)

INSERT INTO [SUPERMERCADO].[dbo].[DEPARTAMENTO]
	VALUES (28,'TOLEDO',7)



--TABLA CIUDAD

--HONDURAS
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (1,'SAN PEDRO SULA',1)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (2,'PUERTO LEMPIRA',2)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (3,'SANTA ROSA DE COPAN',3)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (4,'YORO',4)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (5,'JUTICALPA',5)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (6,'GRACIAS',6)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (7,'OCOTEPEQUE',7)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (8,'NACAOME',8)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (9,'TEGUCIGALPA',9)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (10,'CHOLUTECA',10)


--NIGARAGUA
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (11,'LEON',11)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (12,'MANAGUA',12)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (13,'MASAYA',13)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (14,'GRANADA',14)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (15,'RIVAS',15)


--EL SALVADOR
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (16,'SAN SALVADOR',16)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (17,'COJUTEPEQUE',17)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (18,'SAN FRANCISCO',18)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (19,'SANTA TECLA',19)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (20,'SAN MIGUEL',20)


--COSTA RICA
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (21,'SAN JOSE',21)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (22,'CARTAGO',22)


--PANAMA
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (23,'PANAMA',23)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (24,'COLON',24)


--GUATEMALA
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (25,'GUATEMALA',25)


--BELICE
INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (26,'SAN IGNACIO',26)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (27,'CIUDAD DE BELICE',27)

INSERT INTO [SUPERMERCADO].[dbo].[CIUDAD]
	VALUES (28,'PUNTA GORDA',28)



--TABLA SUCURSAL


--HONDURAS
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (1,'SAN PEDRO SULA',1)

INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (2,'NACAOME',8)

INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (3,'TEGUCIGALPA',9)

INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (4,'CHOLUTECA',10)


--NIGARAGUA
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (5,'LEON',11)


--EL SALVADOR
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (6,'SAN SALVADOR',16)


--COSTA RICA
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (7,'SAN JOSE',21)


--PANAMA
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (8,'PANAMA',23)


--GUATEMALA
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (9,'GUATEMALA',25)


--BELICE
INSERT INTO [SUPERMERCADO].[dbo].[SUCURSAL]
	VALUES (10,'SUCURSAL DE BELICE',27)



--TABLA PROVEEDOR

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (1,'GRUPO PROA')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (2,'FERJUSANZ')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (3,'AXARFRUIT')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (4,'COFRUBAR')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (5,'MYG FRUVERCARNES')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (6,'AGROVER SRL')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (7,'PARBORIZ SPA')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (8,'RICHFIELD CORPORATION LIMITED')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (9,'SCHEPENS')
	
INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (10,'CAVENTEK')
	
INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (11,'PORTALCONSA')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (12,'SULA')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (13,'AGROPECUARIA MOLINA')

INSERT INTO [SUPERMERCADO].[dbo].[PROVEEDOR]
	VALUES (14,'LACTEOS LA ROSA')



--TABLA TIPO_PRODUCTO

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (1,'FRUTAS Y VERDURAS','CONSUMO DOMESTICO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (2,'LACTEOS','CONSUMO DOMESTICO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (3,'CARNES','CONSUMO DOMESTICO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (4,'DULCES','CONSUMO DOMESTICO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (5,'BEBIDAS','CONSUMO DOMESTICO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (6,'ACEITE VEGETAL','CONSUMO DOMESTICO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_PRODUCTO]
	VALUES (7,'LIMPIEZA','ASEO')


--TABLA PRODUCTO

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (1,'ACEITE DE GIRASOL','2014-10-12','2015-11-20',67,81,450,'CONSUMO DOMESTICO',6,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (2,'DETERGENTE EN POLVO','2014-12-12','2016-11-20',48,67,1823,'ASEO',7,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (3,'LECHE','2015-04-12','2015-11-10',16.3,19.98,700,'CONSUMO DOMESTICO',2,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (4,'JABON','2012-01-12','2016-05-05',9.8,17.78,2908,'PRODUCTO EN BARRA',7,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (5,'JUGO DE NARANJA','2015-01-12','2015-11-20',23.5,31.6,2000,'CONSUMO DOMESTICO',5,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (6,'PAPEL SANITARIO','2014-10-12','2018-11-20',34.95,49.28,3000,'CUATRO ROLLOS',7,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (7,'MANZANA ROJA','2015-04-12','2015-11-20',10,21,550,'CONSUMO DOMESTICO',1,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (8,'CHOCOLATE BLANO','2014-10-12','2015-11-20',102.1,132,655,'CONSUMO DOMESTICO',4,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (9,'ZANAHORIA','2015-10-12','2015-11-20',5,9.5,500,'CONSUMO DOMESTICO',1,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (10,'AGUA','2014-04-12','2016-1-20',17.6,23.5,1000,'CONSUMO DOMESTICO UN LITRO ',5,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (11,'QUESILLO','2015-04-12','2015-11-10',16.3,19.98,610,'CONSUMO DOMESTICO',2,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (12,'MATEQUILLA','2015-04-12','2015-11-10',16.3,19.98,970,'CONSUMO DOMESTICO',2,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (13,'MANZANA VERDE','2015-04-12','2015-11-20',10,21,550,'CONSUMO DOMESTICO',1,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (14,'PALETAS DE FRESA','2014-04-04','2015-08-04',43.1,67,785,'BOLSA 20 UNIDADES',4,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO]
VALUES (15,'PESCADO','2015-04-04','2015-08-04',71.1,83,185,'CONSUMO DOMESTICO',3,1)



--TABLA PRODUCTO_PROVEEDOR

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(1,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(2,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(3,12)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(4,4)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(5,6)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(6,8)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(7,7)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(8,9)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(9,10)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(10,1)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(11,14)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(12,14)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(13,2)

INSERT INTO [SUPERMERCADO].[dbo].[PRODUCTO_PROVEEDOR]
	VALUES(14,2)



--TABLA SEXO

INSERT INTO [SUPERMERCADO].[dbo].[SEXO]
	VALUES(1,'MASCULINO')

INSERT INTO [SUPERMERCADO].[dbo].[SEXO]
	VALUES(2,'FEMENINO')



--TABLA CARGA_LABORAL

INSERT INTO [SUPERMERCADO].[dbo].[CARGO_LABORAL]
	VALUES(1,'CAJERO','REALIZADA LA FACTURACION DE LAS VENTAS',10500)

INSERT INTO [SUPERMERCADO].[dbo].[CARGO_LABORAL]
	VALUES(2,'GERENTE DE VENTAS','SUPERVISA LAS VENTAS',31000)



--TABLA PERSONA

--EMPLEADOS
INSERT INTO [SUPERMERCADO].[dbo].[PERSONA]
VALUES(1,'ERICK','FABRICIO','MARTINEZ','CASTELLANOS','1995-11-10','0801-1995-23731','COL.ARTURO QUEZADA',9,1)

INSERT INTO [SUPERMERCADO].[dbo].[PERSONA]
VALUES(2,'JUAN','PEDRO','MENDOZA','VALLE','1990-01-07','0801-1990-89761','COL.LA ROZA',9,1)

INSERT INTO [SUPERMERCADO].[dbo].[PERSONA]
VALUES(3,'MARIA','SOLEDAD','BONILLA','LOPEZ','1989-05-05','0801-1989-98761','COL. SANTA MONICA',9,1)

--CLIENTES
INSERT INTO [SUPERMERCADO].[dbo].[PERSONA]
VALUES(4,'LUIS','FERNANDO','BACA','CASTELLANOS','1991-11-10','0801-1991-56731','COL.LOS PINOS',9,1)

INSERT INTO [SUPERMERCADO].[dbo].[PERSONA]
VALUES(5,'CINTIA','PAOLA','PEREZ','PEREZ','1992-02-21','0801-1992-22131','COL.SUYAPA',9,1)



--TABLA EMPLEADO

INSERT INTO [SUPERMERCADO].[dbo].[EMPLEADO]
	VALUES(1,'2012-03-08',45,1,2,1)

INSERT INTO [SUPERMERCADO].[dbo].[EMPLEADO]
	VALUES(2,'2014-11-10',60,2,1,1)

INSERT INTO [SUPERMERCADO].[dbo].[EMPLEADO]
	VALUES(3,'2015-07-07',60,3,1,1)



--TABLA CLIENTE

INSERT INTO [SUPERMERCADO].[dbo].[CLIENTE]
	VALUES(1,4)

INSERT INTO [SUPERMERCADO].[dbo].[CLIENTE]
	VALUES(2,5)



--TABLA TELEFONO

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_TELEFONO]
	VALUES(1,'CASA','FIJO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_TELEFONO]
	VALUES(2,'TRABAJO','FIJO')

INSERT INTO [SUPERMERCADO].[dbo].[TIPO_TELEFONO]
	VALUES(3,'MOVIL','PERSONAL')



--TABLA TELEFONO

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(1,'504 8982-4703',3,1)

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(2,'504 2324-4735',1,1)

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(3,'504 2526-2987',2,1)

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(4,'504 2888-3453',1,2)

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(5,'504 2453-6678',1,3)

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(6,'504 2348-4768',1,4)

INSERT INTO [SUPERMERCADO].[dbo].[TELEFONO]
	VALUES(7,'504 2775-4120',1,5)



--TABLA FACTURA

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA]
	VALUES(1,'2015-01-01',1,1,2)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA]
	VALUES(2,'2015-01-01',1,2,2)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA]
	VALUES(3,'2015-01-10',1,2,1)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA]
	VALUES(4,'2015-01-11',1,1,1)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA]
	VALUES(5,'2015-01-20',1,1,2)



--TABLA FACTURA_PRODUCTO

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(1,1,2)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(1,2,1)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(1,3,3)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(2,5,1)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(3,6,1)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(4,7,1)

INSERT INTO [SUPERMERCADO].[dbo].[FACTURA_PRODUCTO]
	VALUES(5,10,4)

